"""Parses roadmap/items/*.md and renders the index block in roadmap/README.md.

Each item is one Markdown file whose TOML frontmatter -- fenced by `+++`, read
by the stdlib's tomllib, so the package keeps its zero-dependency dev set --
carries the fields a reader would otherwise have to infer from prose: which
bucket it is in, what gates it, and which changes, specs and files it touches.
The prose body is untouched by this module; it is where the argument lives and
no schema should try to eat it.

Run `python tools/roadmap_index.py` to rewrite the index; tests/test_roadmap.py
fails if what is committed differs from what this renders, so the index cannot
drift from the items it summarises."""

from __future__ import annotations

import datetime
import glob
import re
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ITEMS_DIR = Path("roadmap/items")
README = Path("roadmap/README.md")
BEGIN = "<!-- BEGIN INDEX: generated by tools/roadmap_index.py; edit roadmap/items/*.md instead -->"
END = "<!-- END INDEX -->"

BUCKETS = ("now", "next", "later")
BUCKET_TITLES = {"now": "Now", "next": "Next", "later": "Later"}
REQUIRED = {"id", "title", "bucket", "rank", "filed"}
OPTIONAL = {"claimed", "updated", "gate", "blocked_on", "refs"}
REF_KINDS = ("changes", "specs", "files")

_FRONTMATTER = re.compile(r"\A\+\+\+\n(.*?)\n\+\+\+\n(.*)\Z", re.DOTALL)


@dataclass(frozen=True)
class Item:
    path: Path
    meta: dict
    body: str

    @property
    def id(self) -> str:
        return str(self.meta.get("id", self.path.stem))

    @property
    def title(self) -> str:
        return str(self.meta.get("title", self.id))

    @property
    def bucket(self) -> str:
        return str(self.meta.get("bucket", ""))

    @property
    def rank(self) -> int:
        return int(self.meta.get("rank", 0))


def parse(path: Path) -> Item:
    """One item file into its metadata and its prose. Raises ValueError with the
    path in the message on anything tomllib or the fence rejects, since every
    caller is either a test or a script reporting straight to a human."""
    match = _FRONTMATTER.match(path.read_text())
    if match is None:
        raise ValueError(f"{path}: no +++-fenced TOML frontmatter at the top of the file")
    try:
        meta = tomllib.loads(match.group(1))
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"{path}: malformed TOML frontmatter: {exc}") from exc
    return Item(path=path, meta=meta, body=match.group(2))


def load() -> list[Item]:
    """Every item, ordered as the index renders them: by bucket, then by rank."""
    items = [parse(Path(p)) for p in sorted(glob.glob(str(ITEMS_DIR / "*.md")))]
    return sorted(items, key=lambda i: (BUCKETS.index(i.bucket) if i.bucket in BUCKETS else len(BUCKETS), i.rank))


def validate(items: list[Item], root: Path = Path()) -> list[str]:
    """Every rule the frontmatter has to satisfy, as a list of complaints. An
    empty list is a clean roadmap. Collects rather than raises so one run
    reports every problem instead of the first."""
    problems = []
    for item in items:
        problems.extend(_schema_problems(item))
        problems.extend(_bucket_problems(item))
        problems.extend(_date_problems(item))
        problems.extend(_broken_refs(item, root))
    return problems + _collision_problems(items)


def _schema_problems(item: Item) -> list[str]:
    """The fields themselves: all of the required ones, none unknown, and an id
    that agrees with the filename so a file can be found from an index entry."""
    problems = []
    fields = set(item.meta)
    if missing := REQUIRED - fields:
        problems.append(f"{item.path}: missing required field(s) {', '.join(sorted(missing))}")
    if unknown := fields - REQUIRED - OPTIONAL:
        problems.append(f"{item.path}: unknown field(s) {', '.join(sorted(unknown))}")
    if item.id != item.path.stem:
        problems.append(f"{item.path}: id {item.id!r} does not match its filename")
    return problems


def _bucket_problems(item: Item) -> list[str]:
    """The entry criteria, enforced rather than described. Later is the bucket
    for the undecided, so an item there names the decision it is waiting on;
    anywhere else, naming one contradicts the bucket. Next is the bucket for the
    claimed, and Now is explicitly a pool of the unclaimed."""
    if item.bucket not in BUCKETS:
        return [f"{item.path}: bucket {item.bucket!r} is not one of {', '.join(BUCKETS)}"]

    problems = []
    blocked, claimed = item.meta.get("blocked_on"), item.meta.get("claimed")
    if item.bucket == "later" and not blocked:
        problems.append(f"{item.path}: a 'later' item must name what it is blocked_on")
    if item.bucket != "later" and blocked:
        problems.append(f"{item.path}: blocked_on belongs to a 'later' item; this one is {item.bucket!r}")
    if item.bucket == "next" and not claimed:
        problems.append(f"{item.path}: a 'next' item must carry the date it was claimed")
    if item.bucket == "now" and claimed:
        problems.append(f"{item.path}: a claimed item belongs in 'next', not 'now'")
    return problems


def _date_problems(item: Item) -> list[str]:
    """A bare TOML date parses to datetime.date; a quoted one parses to str and
    sorts and renders wrong. The distinction is invisible in the file, so it is
    worth a check."""
    return [
        f"{item.path}: {field} must be a bare TOML date (2026-09-06), not {item.meta[field]!r}"
        for field in ("filed", "claimed", "updated")
        if field in item.meta and not isinstance(item.meta[field], datetime.date)
    ]


def _collision_problems(items: list[Item]) -> list[str]:
    """What only the whole set can see: two files claiming one id, or two items
    claiming one position in a bucket."""
    problems = []
    seen: dict[str, Path] = {}
    ranks: dict[tuple[str, int], Path] = {}
    for item in items:
        if (first := seen.setdefault(item.id, item.path)) is not item.path:
            problems.append(f"{item.path}: duplicate id {item.id!r}, also in {first}")
        key = (item.bucket, item.rank)
        if (other := ranks.setdefault(key, item.path)) is not item.path:
            problems.append(f"{item.path}: rank {item.rank} is already taken in {item.bucket!r} by {other}")
    return problems


def _broken_refs(item: Item, root: Path) -> list[str]:
    """Every ref pointing at something that is not there. This is the half of
    the check prose could never do: an openspec change id, a spec id or a source
    path named in an item is resolved against the tree, so a rename breaks the
    build rather than quietly rotting the roadmap."""
    refs = item.meta.get("refs", {})
    if not isinstance(refs, dict):
        return [f"{item.path}: refs must be a table of {'/'.join(REF_KINDS)} lists"]

    problems = []
    if unknown := set(refs) - set(REF_KINDS):
        problems.append(f"{item.path}: unknown ref kind(s) {', '.join(sorted(unknown))}")

    for change in refs.get("changes", []):
        active = root / "openspec/changes" / change
        archived = glob.glob(str(root / "openspec/changes/archive" / f"*-{change}"))
        if not active.is_dir() and not archived:
            problems.append(f"{item.path}: refs.changes {change!r} is neither an active nor an archived change")
    problems.extend(
        f"{item.path}: refs.specs {spec!r} is not a spec in openspec/specs"
        for spec in refs.get("specs", [])
        if not (root / "openspec/specs" / spec).is_dir()
    )
    problems.extend(
        f"{item.path}: refs.files {path!r} does not exist" for path in refs.get("files", []) if not (root / path).exists()
    )
    return problems


def render(items: list[Item]) -> str:
    """The index block, between its markers. One line per item, and nothing a
    reader has to trust: everything here is read back out of the item files."""
    lines = [BEGIN, ""]
    for bucket in BUCKETS:
        in_bucket = [i for i in items if i.bucket == bucket]
        lines.append(f"### {BUCKET_TITLES[bucket]} ({len(in_bucket)})")
        lines.append("")
        if not in_bucket:
            lines.extend(["*Empty.*", ""])
            continue
        for item in in_bucket:
            note = _note(item)
            lines.append(f"{item.rank}. [{item.title}](items/{item.path.name}) — filed {item.meta['filed']}{note}")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def _note(item: Item) -> str:
    if blocked := item.meta.get("blocked_on"):
        return f"<br>  **Blocked on:** {blocked}"
    if gate := item.meta.get("gate"):
        return f"<br>  **Gate:** {gate}"
    return ""


def readme_with_index(items: list[Item], readme: Path = README) -> str:
    """The README as it should be on disk: its prose, with the generated block
    replaced. Refuses a README missing the markers rather than guessing where
    the index goes."""
    text = readme.read_text()
    start, end = text.find(BEGIN), text.find(END)
    if start == -1 or end == -1:
        raise ValueError(f"{readme}: index markers not found; expected {BEGIN} ... {END}")
    return text[:start] + render(items) + text[end + len(END) :]


def main() -> int:
    items = load()
    if problems := validate(items):
        print("\n".join(problems), file=sys.stderr)
        return 1
    README.write_text(readme_with_index(items))
    print(f"Wrote {README} from {len(items)} item(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
